### ISSUE TITLE
Actualizar/Implementar roles en la lógica del programa

### ISSUE THREAD

**Issue by ELLOQUIUS** [USB-CI3715/nodebb-usb-24-digitalpioneers#11]
Actualizar las permisoligías de NodeBB para que se basen en roles de tipo estudiante/profesor, o por el contrario, si no están implementadas, implementar la lógica.

Tareas:

* Revisar si existe la función de permisologías (roles) en NodeBB.
* En caso de que exista esta función, actualizarla para que función con los roles estudiante/profesor
* En caso de que no exista esta función, implementarla en la lógica del programa

Esfuerzo estimado: Alto.

Estimación: Segundo Sprint

Independencia: Este Issue es independiente (si se desea probar el funcionamiento correctamente, es necesario haber realizado el Issue #13 ).

**Comment by KevinJOH** [comment]
Ya se implementó, pero en la PR se hizo mención a otro issue que tenía una descripción similar
