### ISSUE TITLE
Implementar roles en la base de datos

### ISSUE THREAD

**Issue by ELLOQUIUS** [USB-CI3715/nodebb-usb-24-digitalpioneers#13]
Agregar en la base de datos, la funcionalidad de roles, asi como los atributos necesarios.

Tareas:

* Agregar la tabla rol (en caso de ser necesario) a la base de datos
* Agregar los atributos necesarios a la(s) tabla(s) creada(s). 
* Implementar la lógica necesaria (en caso de no haberla) en la base de datos de las permisologías/roles.

Esfuerzo estimado: Moderado.

Estimación: Segundo Sprint

Independencia: Este Issue es independiente.

**Comment by KevinJOH** [comment]
Se decidió por otro método de implementación de roles, donde no era necesario atender este issue
